name: Deploy Python Package to PyPI

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Choose the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Install packaging tools

      # Step 4: Build the package
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel  # Build the source distribution and wheel

      # Step 5: Deploy to PyPI
      - name: Deploy to PyPI
        run: |
          twine upload dist/*  # Upload all distribution files
        env:
          TWINE_USERNAME: __token__  # Use PyPI token as username
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Your PyPI API token stored in GitHub secrets
